<!--
* Autor: Camilo Figueroa ( Crivera )
* Vista: sección tomar foto.
*
-->


<br>

<h1>Selecciona alguna de tus cámaras.</h1>
<div>
    <select name="listaDeDispositivos" id="listaDeDispositivos"></select>
    <button id="boton">Tomar foto</button>
    <p id="estado"></p>
</div>
<br>
<div id="contenedor-visor">
    <video muted="muted" id="video"></video>
    <canvas id="canvas" style="display: none;"></canvas>
</div>

<!-- Tocó colocar el script aquí para que solo afectara esta sección.-->
<script src="../js/script.js"></script>